version: '1'
services:
  app:
    image: /socks-shop
    ports:
      - '8080:8080'
  db:
    image: postgres:13.11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'